name: Check URLs

on:
  push:
    branches:
      - url_checker
jobs:
  urlchecks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: URLs-checker
      uses: urlstechie/urlchecker-action@master
      with:
        # A comma-separated list of file types to cover in the URL checks
        file_types: .rst,.md,.py,.ipynb

        # Choose whether to include file with no URLs in the prints.
        print_all: false

        # Timeout in 10 seconds if url is not reached
        timeout: 10

        # How many times to retry a failed request (each is logged, defaults to 1)
        retry_count: 3

